const countries = [
    {name:'RÚSSIA',flag:'https://flags.fmcdn.net/data/flags/w580/ru.png',capital:'Moscou',continent:'Europa'},
    {name:'BRASIL',flag:'https://flags.fmcdn.net/data/flags/w580/br.png',capital:'Brasília',continent:'América do Sul'},
    {name:'IRÃ',flag:'https://flags.fmcdn.net/data/flags/w580/ir.png',capital:'Teerã',continent:'Ásia'},
    {name:'JAPÃO',flag:'https://flags.fmcdn.net/data/flags/w580/jp.png',capital:'Tóquio',continent:'Ásia'},
    {name:'MÉXICO',flag:'https://flags.fmcdn.net/data/flags/w580/mx.png',capital:'Cidade do México',continent:'América Central e do Norte'},
    {name:'BÉLGICA',flag:'https://flags.fmcdn.net/data/flags/w580/be.png',capital:'Bruxelas',continent:'Europa'},
    {name:'CORREIA DO SUL',flag:'https://flags.fmcdn.net/data/flags/w580/kr.png',capital:'Seul',continent:'Ásia'},
    {name:'ARÁBIA SAUDITA',flag:'https://flags.fmcdn.net/data/flags/w580/sa.png',capital:'Riade',continent:'Ásia'},
    {name:'ALEMANHA',flag:'https://flags.fmcdn.net/data/flags/w580/de.png',capital:'Berlim',continent:'Europa'},
    {name:'INGLATERRA',flag:'https://flags.fmcdn.net/data/flags/w580/gb.png',capital:'Londres',continent:'Europa'},
    {name:'ESPANHA',flag:'https://flags.fmcdn.net/data/flags/w580/es.png',capital:'Madri',continent:'Europa'},
    {name:'NIGÉRIA',flag:'https://flags.fmcdn.net/data/flags/w580/ng.png',capital:'Abuja',continent:'África'},
    {name:'COSTA RICA',flag:'https://flags.fmcdn.net/data/flags/w580/cr.png',capital:'San Jóse',continent:'América Central e do Norte'},
    {name:'POLÔNIA',flag:'https://flags.fmcdn.net/data/flags/w580/pl.png',capital:'Varsóvia',continent:'Europa'},
    {name:'EGITO',flag:'https://flags.fmcdn.net/data/flags/w580/eg.png',capital:'Cairo',continent:'África'},
    {name:'SÉRVIA',flag:'https://flags.fmcdn.net/data/flags/w580/rs.png',capital:'Belgrado',continent:'Europa'},
    {name:'ISLÂNDIA',flag:'https://flags.fmcdn.net/data/flags/w580/is.png',capital:'Reykjavík',continent:'Europa'},
    {name:'FRANÇA',flag:'https://flags.fmcdn.net/data/flags/w580/fr.png',capital:'Paris',continent:'Europa'},
    {name:'PORTUGAL',flag:'https://flags.fmcdn.net/data/flags/w580/pt.png',capital:'Lisboa',continent:'Europa'},
    {name:'URUGUAI',flag:'https://flags.fmcdn.net/data/flags/w580/uy.png',capital:'Montevidéu',continent:'América do Sul'},
    {name:'ARGENTINA',flag:'https://flags.fmcdn.net/data/flags/w580/ar.png',capital:'Buenos Aires',continent:'América do Sul'},
    {name:'COLÔMBIA',flag:'https://flags.fmcdn.net/data/flags/w580/co.png',capital:'Bogotá',continent:'América do Sul'},
    {name:'PANAMÁ',flag:'https://flags.fmcdn.net/data/flags/w580/pa.png',capital:'Cidade do Panamá',continent:'América Central e do Norte'},
    {name:'SENEGAL',flag:'https://flags.fmcdn.net/data/flags/w580/sn.png',capital:'Dakar',continent:'África'},
    {name:'MARROCOS',flag:'https://flags.fmcdn.net/data/flags/w580/ma.png',capital:'Rabat',continent:'África'},
    {name:'TUNÍSIA',flag:'https://flags.fmcdn.net/data/flags/w580/tn.png',capital:'Tunis',continent:'África'},
    {name:'CROÁCIA',flag:'https://flags.fmcdn.net/data/flags/w580/hr.png',capital:'Zagreb',continent:'Europa'},
    {name:'SUÍÇA',flag:'https://flags.fmcdn.net/data/flags/w580/ch.png',capital:'Bern',continent:'Europa'},
    {name:'SUÉCIA',flag:'https://flags.fmcdn.net/data/flags/w580/se.png',capital:'Estocolmo',continent:'Europa'},
    {name:'DINAMARCA',flag:'https://flags.fmcdn.net/data/flags/w580/dk.png',capital:'Copenhague',continent:'Europa'},
    {name:'AUSTRÁLIA',flag:'https://flags.fmcdn.net/data/flags/w580/au.png',capital:'Canberra',continent:'Oceania'},
    {name:'PERU',flag:'https://flags.fmcdn.net/data/flags/w580/pe.png',capital:'Lima',continent:'América do Sul'}
]
